name: pcf-registry

services:
  minio:
    image: minio/minio #quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server ${MINIO_VOLUMES} --console-address ":9001"
    networks:
      - internal
    volumes:
      - minio_data:${MINIO_VOLUMES}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  flask-pcf:
    build: .
    container_name: pcf-registry
    ports:
      - "5000:5000"
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
    volumes:
      - .:/app
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  minio_data: