# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: json_streaming.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'json_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14json_streaming.proto\"\x19\n\tJsonChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\nGetRequest\x12\x0f\n\x07message\x18\x01 \x01(\t2i\n\x14JsonStreamingService\x12+\n\nUploadJson\x12\n.JsonChunk\x1a\x0f.UploadResponse(\x01\x12$\n\x07GetJson\x12\x0b.GetRequest\x1a\n.JsonChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'json_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONCHUNK']._serialized_start=24
  _globals['_JSONCHUNK']._serialized_end=49
  _globals['_UPLOADRESPONSE']._serialized_start=51
  _globals['_UPLOADRESPONSE']._serialized_end=101
  _globals['_GETREQUEST']._serialized_start=103
  _globals['_GETREQUEST']._serialized_end=132
  _globals['_JSONSTREAMINGSERVICE']._serialized_start=134
  _globals['_JSONSTREAMINGSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
