apiVersion: v2
name: pcf-registry
description: A Helm chart for the Flask-based pcf-registry microservice
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: traefik
    version: 25.0.0
    repository: https://traefik.github.io/charts