namespace: pcf-registry

pcfRegistry:
  image: pcf-registry:latest
  replicas: 1
  containerPort: 5002
  servicePort: 80
  pcfAppName: pcf-registry-service

minio:
  image: quay.io/minio/minio:latest
  replicas: 1
  rootUser: minioadmin
  rootPassword: minioadmin
  consolePort: 9001
  apiPort: 9000
  minioAppName: minio-server

ingress:
  host: pcf-registry.local