apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.minio.minioAppName }}
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.minio.minioAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.minio.minioAppName }}
    spec:
      containers:
      - name: minio
        image: {{ .Values.minio.image }}
        args: ["server", "/data", "--console-address", ":{{ .Values.minio.consolePort }}"]
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.rootUser }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.minio.rootPassword }}
        ports:
        - containerPort: {{ .Values.minio.apiPort }}
        - containerPort: {{ .Values.minio.consolePort }}
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}