apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pcf-registry-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.httpHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pcf-registry-service
            port:
              number: {{ .Values.pcfRegistry.servicePorts.http }}

  - host: {{ .Values.ingress.grpcHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pcf-registry-service
            port:
              number: {{ .Values.pcfRegistry.servicePorts.grpc }}