apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.minio.minioAppName }}
  ports:
  - name: api
    port: {{ .Values.minio.apiPort }}
    targetPort: {{ .Values.minio.apiPort }}
  - name: console
    port: {{ .Values.minio.consolePort }}
    targetPort: {{ .Values.minio.consolePort }}