apiVersion: v1
kind: Service
metadata:
  name: pcf-registry-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.pcfRegistry.pcfAppName }}
  ports:
  - name: http
    port: {{ .Values.pcfRegistry.servicePort }}
    targetPort: 5002
    protocol: TCP
  - name: grpc
    port: 50052
    targetPort: 50052
    protocol: TCP