apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pcf-registry-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.240-192.168.1.250  # your desired IP range

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - pcf-registry-ip-pool